package com.mxl.education.question.bean

import java.sql.Timestamp

import org.apache.commons.net.ntp.TimeStamp


case class DwdQzChapter(
	                       chapterid: Int,
	                       chapterlistid: Int,
	                       chaptername: String,
	                       sequence: String,
	                       showstatus: String,
	                       creator: String,
	                       createtime: Timestamp,
	                       courseid: Int,
	                       chapternum: Int,
	                       outchapterid: Int,
	                       dt: String,
	                       dn: String)


case class DwdQzChapterList(
	                            chapterlistid: Int,
	                            chapterlistname: String,
	                            courseid: Int,
	                            chapterallnum: Int,
	                            sequence: String,
	                            status: String,
	                            creator: String,
	                            createtime: Timestamp,
	                            dt: String,
	                            dn: String)


case class DwdQzPoint(
	                     pointid: Int,
	                     courseid: Int,
	                     pointname: String,
	                     pointyear: String,
	                     chapter: String,
	                     creator: String,
	                     createtme: Timestamp,
	                     status: String,
	                     modifystatus: String,
	                     excisenum: Int,
	                     pointlistid: Int,
	                     chapterid: Int,
	                     sequence: String,
	                     pointdescribe: String,
	                     pointlevel: String,
	                     typelist: String,
	                     score: BigDecimal,
	                     thought: String,
	                     remid: String,
	                     pointnamelist: String,
	                     typelistids: String,
	                     pointlist: String,
	                     dt: String,
	                     dn: String)


case class DwdQzPointQuestion(
	                             pointid: Int,
	                             questionid: Int,
	                             questype: Int,
	                             creator: String,
	                             createtime: String,
	                             dt: String,
	                             dn: String)


case class DwdQzSiteCourse(
	                          sitecourseid: Int,
	                          siteid: Int,
	                          courseid: Int,
	                          sitecoursename: String,
	                          coursechapter: String,
	                          sequence: String,
	                          status: String,
	                          creator: String,
	                          createtime: Timestamp,
	                          helppaperstatus: String,
	                          servertype: String,
	                          boardid: Int,
	                          showstatus: String,
	                          dt: String,
	                          dn: String)


case class DwdQzCourse(
	                      courseid: Int,
	                      majorid: Int,
	                      coursename: String,
	                      coursechapter: String,
	                      sequence: String,
	                      isadvc: String,
	                      creator: String,
	                      createtime: Timestamp,
	                      status: String,
	                      chapterlistid: Int,
	                      pointlistid: Int,
	                      dt: String,
	                      dn: String)


case class DwdQzCourseEdusubject(
	                                courseeduid: Int,
	                                edusubjectid: Int,
	                                courseid: Int,
	                                creator: String,
	                                createtime: Timestamp,
	                                majorid: Int,
	                                dt: String,
	                                dn: String)


case class DwdQzWebsite(
	                       siteid: Int,
	                       sitename: String,
	                       domain: String,
	                       sequence: String,
	                       multicastserver: String,
	                       templateserver: String,
	                       status: String,
	                       creator: String,
	                       createtime: Timestamp,
	                       multicastgateway: String,
	                       multicastport: String,
	                       dt: String,
	                       dn: String)


case class DwdQzMajor(
	                     majorid: Int,
	                     businessid: Int,
	                     siteid: Int,
	                     majorname: String,
	                     shortname: String,
	                     status: String,
	                     sequence: String,
	                     creator: String,
	                     createtime: Timestamp,
	                     column_sitetype: String,
	                     dt: String,
	                     dn: String)


case class DwdQzBusiness(
	                        businessid: Int,
	                        businessname: String,
	                        sequence: String,
	                        status: String,
	                        creator: String,
	                        createtime: Timestamp,
	                        siteid: Int,
	                        dt: String,
	                        dn: String)


case class DwdQzPaperView(
	                         paperviewid: Int,
	                         paperid: Int,
	                         paperviewname: String,
	                         paperparam: String,
	                         openstatus: String,
	                         explainurl: String,
	                         iscontest: String,
	                         contesttime: Timestamp,
	                         conteststarttime: Timestamp,
	                         contestendtime: Timestamp,
	                         contesttimelimit: String,
	                         dayiid: Int,
	                         status: String,
	                         creator: String,
	                         createtime: Timestamp,
	                         paperviewcatid: Int,
	                         modifystatus: String,
	                         description: String,
	                         papertype: String,
	                         downurl: String,
	                         paperuse: String,
	                         paperdifficult: String,
	                         testreport: String,
	                         paperuseshow: String,
	                         dt: String,
	                         dn: String)


case class DwdQzCenterPaper(
	                           paperviewid: Int,
	                           centerid: Int,
	                           openstatus: String,
	                           sequence: String,
	                           creator: String,
	                           createtime: Timestamp,
	                           dt: String,
	                           dn: String)


case class DwdQzPaper(
	                     paperid: Int,
	                     papercatid: Int,
	                     courseid: Int,
	                     paperyear: String,
	                     chapter: String,
	                     suitnum: String,
	                     papername: String,
	                     status: String,
	                     creator: String,
	                     createtime: Timestamp,
	                     totalscore: BigDecimal,
	                     chapterid: Int,
	                     chapterlistid: Int,
	                     dt: String,
	                     dn: String)


case class DwdQzCenter(
	                      centerid: Int,
	                      centername: String,
	                      centeryear: String,
	                      centertype: String,
	                      openstatus: String,
	                      centerparam: String,
	                      description: String,
	                      creator: String,
	                      createtime: Timestamp,
	                      sequence: String,
	                      provideuser: String,
	                      centerviewtype: String,
	                      stage: String,
	                      dt: String,
	                      dn: String)


case class DwdQzQuestion(
	                        questionid: Int,
	                        parentid: Int,
	                        questypeid: Int,
	                        quesviewtype: Int,
	                        content: String,
	                        answer: String,
	                        analysis: String,
	                        limitminute: String,
	                        score: BigDecimal,
	                        splitscore: BigDecimal,
	                        status: String,
	                        optnum: Int,
	                        lecture: String,
	                        creator: String,
	                        createtime: String,
	                        modifystatus: String,
	                        attanswer: String,
	                        questag: String,
	                        vanalysisaddr: String,
	                        difficulty: String,
	                        quesskill: String,
	                        vdeoaddr: String,
	                        dt: String,
	                        dn: String)


case class DwdQzQuestionType(
	                            quesviewtype: Int,
	                            viewtypename: String,
	                            questypeid: Int,
	                            description: String,
	                            status: String,
	                            creator: String,
	                            createtime: Timestamp,
	                            papertypename: String,
	                            sequence: String,
	                            remark: String,
	                            splitscoretype: String,
	                            dt: String,
	                            dn: String)


case class DwdQzMemberPaperQuestion(
	                                   userid: Int,
	                                   paperviewid: Int,
	                                   chapterid: Int,
	                                   sitecourseid: Int,
	                                   questionid: Int,
	                                   majorid: Int,
	                                   useranswer: String,
	                                   istrue: String,
	                                   lasttime: Timestamp,
	                                   opertype: String,
	                                   paperid: Int,
	                                   spendtime: Int,
	                                   score: BigDecimal,
	                                   question_answer: Int,
	                                   dt: String,
	                                   dn: String)


case class DwsQzChapter(
	                       chapterid: Int,
	                       chapterlistid: Int,
	                       chaptername: String,
	                       sequence: String,
	                       showstatus: String,
	                       status: String,
	                       chapter_creator: String,
	                       chapter_createtime: String,
	                       chapter_courseid: Int,
	                       chapternum: Int,
	                       chapterallnum: Int,
	                       outchapterid: Int,
	                       chapterlistname: String,
	                       pointid: Int,
	                       questionid: Int,
	                       questype: Int,
	                       pointname: String,
	                       pointyear: String,
	                       chapter: String,
	                       excisenum: Int,
	                       pointlistid: Int,
	                       pointdescribe: String,
	                       pointlevel: String,
	                       typelist: String,
	                       point_score: BigDecimal,
	                       thought: String,
	                       remid: String,
	                       pointnamelist: String,
	                       typelistids: String,
	                       pointlist: String,
	                       dt: String,
	                       dn: String)


case class DwsQzCourse(
	                      sitecourseid: Int,
	                      siteid: Int,
	                      courseid: Int,
	                      sitecoursename: String,
	                      coursechapter: String,
	                      sequence: String,
	                      status: String,
	                      sitecourse_creator: String,
	                      sitecourse_createtime: String,
	                      helppaperstatus: String,
	                      servertype: String,
	                      boardid: Int,
	                      showstatus: String,
	                      majorid: Int,
	                      coursename: String,
	                      isadvc: String,
	                      chapterlistid: Int,
	                      pointlistid: Int,
	                      courseeduid: Int,
	                      edusubjectid: Int,
	                      dt: String,
	                      dn: String)


case class DwsQzMajor(
	                     majorid: Int,
	                     businessid: Int,
	                     siteid: Int,
	                     majorname: String,
	                     shortname: String,
	                     status: String,
	                     sequence: String,
	                     major_creator: String,
	                     major_createtime: Timestamp,
	                     businessname: String,
	                     sitename: String,
	                     domain: String,
	                     multicastserver: String,
	                     templateserver: String,
	                     multicastgateway: String,
	                     multicastport: String,
	                     dt: String,
	                     dn: String)


case class DwsQzPaper(
	                     paperviewid: Int,
	                     paperid: Int,
	                     paperviewname: String,
	                     paperparam: String,
	                     openstatus: String,
	                     explainurl: String,
	                     iscontest: String,
	                     contesttime: Timestamp,
	                     conteststarttime: Timestamp,
	                     contestendtime: Timestamp,
	                     contesttimelimit: String,
	                     dayiid: Int,
	                     status: String,
	                     paper_view_creator: String,
	                     paper_view_createtime: Timestamp,
	                     paperviewcatid: Int,
	                     modifystatus: String,
	                     description: String,
	                     paperuse: String,
	                     paperdifficult: String,
	                     testreport: String,
	                     paperuseshow: String,
	                     centerid: Int,
	                     sequence: String,
	                     centername: String,
	                     centeryear: String,
	                     centertype: String,
	                     provideuser: String,
	                     centerviewtype: String,
	                     stage: String,
	                     papercatid: Int,
	                     courseid: Int,
	                     paperyear: String,
	                     suitnum: String,
	                     papername: String,
	                     totalscore: BigDecimal,
	                     chapterid: Int,
	                     chapterlistid: Int,
	                     dt: String,
	                     dn: String)


case class DwsQzQuestion(
	                        questionid: Int,
	                        parentid: Int,
	                        questypeid: Int,
	                        quesviewtype: Int,
	                        content: String,
	                        answer: String,
	                        analysis: String,
	                        limitminute: String,
	                        score: BigDecimal,
	                        splitscore: BigDecimal,
	                        status: String,
	                        optnum: Int,
	                        lecture: String,
	                        creator: String,
	                        createtime: Timestamp,
	                        modifystatus: String,
	                        attanswer: String,
	                        questag: String,
	                        vanalysisaddr: String,
	                        difficulty: String,
	                        quesskill: String,
	                        vdeoaddr: String,
	                        viewtypename: String,
	                        description: String,
	                        papertypename: String,
	                        splitscoretype: String,
	                        dt: String,
	                        dn: String)


case class DwsUserPaperDetail(
	                             userid: Int,
	                             courseid: Int,
	                             questionid: Int,
	                             useranswer: String,
	                             istrue: String,
	                             lasttime: String,
	                             opertype: String,
	                             paperid: Int,
	                             spendtime: Int,
	                             chapterid: Int,
	                             chaptername: String,
	                             chapternum: Int,
	                             chapterallnum: Int,
	                             outchapterid: Int,
	                             chapterlistname: String,
	                             pointid: Int,
	                             questype: Int,
	                             pointyear: String,
	                             chapter: String,
	                             pointname: String,
	                             excisenum: Int,
	                             pointdescribe: String,
	                             pointlevel: String,
	                             typelist: String,
	                             point_score: BigDecimal,
	                             thought: String,
	                             remid: String,
	                             pointnamelist: String,
	                             typelistids: String,
	                             pointlist: String,
	                             sitecourseid: Int,
	                             siteid: Int,
	                             sitecoursename: String,
	                             coursechapter: String,
	                             course_sequence: String,
	                             course_stauts: String,
	                             course_creator: String,
	                             course_createtime: TimeStamp,
	                             servertype: String,
	                             helppaperstatus: String,
	                             boardid: Int,
	                             showstatus: String,
	                             majorid: Int,
	                             coursename: String,
	                             isadvc: String,
	                             chapterlistid: Int,
	                             pointlistid: Int,
	                             courseeduid: Int,
	                             edusubjectid: Int,
	                             businessid: Int,
	                             majorname: String,
	                             shortname: String,
	                             major_status: String,
	                             major_sequence: String,
	                             major_creator: String,
	                             major_createtime: Timestamp,
	                             businessname: String,
	                             sitename: String,
	                             domain: String,
	                             multicastserver: String,
	                             templateserver: String,
	                             multicastgatway: String,
	                             multicastport: String,
	                             paperviewid: Int,
	                             paperviewname: String,
	                             paperparam: String,
	                             openstatus: String,
	                             explainurl: String,
	                             iscontest: String,
	                             contesttime: Timestamp,
	                             conteststarttime: Timestamp,
	                             contestendtime: Timestamp,
	                             contesttimelimit: String,
	                             dayiid: Int,
	                             paper_status: String,
	                             paper_view_creator: String,
	                             paper_view_createtime: Timestamp,
	                             paperviewcatid: Int,
	                             modifystatus: String,
	                             description: String,
	                             paperuse: String,
	                             testreport: String,
	                             centerid: Int,
	                             paper_sequence: String,
	                             centername: String,
	                             centeryear: String,
	                             centertype: String,
	                             provideuser: String,
	                             centerviewtype: String,
	                             paper_stage: String,
	                             papercatid: Int,
	                             paperyear: String,
	                             suitnum: String,
	                             papername: String,
	                             totalscore: BigDecimal,
	                             question_parentid: Int,
	                             questypeid: Int,
	                             quesviewtype: Int,
	                             question_content: String,
	                             question_answer: String,
	                             question_analysis: String,
	                             question_limitminute: String,
	                             score: BigDecimal,
	                             splitscore: BigDecimal,
	                             lecture: String,
	                             question_creator: String,
	                             question_createtime: Timestamp,
	                             question_modifystatus: String,
	                             question_attanswer: String,
	                             question_questag: String,
	                             question_vanalysisaddr: String,
	                             question_difficulty: String,
	                             quesskill: String,
	                             vdeoaddr: String,
	                             question_description: String,
	                             question_splitscoretype: String,
	                             user_question_answer: Int,
	                             dt: String,
	                             dn: String)


case class AdsPaperAvgtimeandscore(
	                                  paperviewid: Int,
	                                  paperviewname: String,
	                                  avgscore: BigDecimal,
	                                  avgspendtime: BigDecimal,
	                                  dt: String,
	                                  dn: String)


case class AdsPaperMaxdetail(
	                            paperviewid: Int,
	                            paperviewname: String,
	                            maxscore: BigDecimal,
	                            minscore: BigDecimal,
	                            dt: String,
	                            dn: String)


case class AdsTop3Userdetail(
	                            userid: Int,
	                            paperviewid: Int,
	                            paperviewname: String,
	                            chaptername: String,
	                            pointname: String,
	                            sitecoursename: String,
	                            coursename: String,
	                            majorname: String,
	                            shortname: String,
	                            papername: String,
	                            score: BigDecimal,
	                            rk: Int,
	                            dt: String,
	                            dn: String)


case class AdsLow3Userdetail(
	                            userid: Int,
	                            paperviewid: Int,
	                            paperviewname: String,
	                            chaptername: String,
	                            pointname: String,
	                            sitecoursename: String,
	                            coursename: String,
	                            majorname: String,
	                            shortname: String,
	                            papername: String,
	                            score: BigDecimal,
	                            rk: Int,
	                            dt: String,
	                            dn: String)


case class AdsPaperScoresegmentUser(
	                                   paperviewid: Int,
	                                   paperviewname: String,
	                                   score_segment: String,
	                                   userids: String,
	                                   dt: String,
	                                   dn: String)


case class AdsUserPaperDetail(
	                             paperviewid: Int,
	                             paperviewname: String,
	                             unpasscount: Int,
	                             passcount: Int,
	                             rate: BigDecimal,
	                             dt: String,
	                             dn: String)


case class AdsUserQuestionDetail(
	                                questionid: Int,
	                                errcount: Int,
	                                rightcount: Int,
	                                rate: BigDecimal,
	                                dt: String,
	                                dn: String)
